version: "3.9"
services:
  mongo:
    container_name: mongo
    image: "mongo:5.0.8-focal"
    restart: always
    volumes:
      - ~/dbdata:/data/db
      - ~/backup/mongo:/backup
    ports:
      - 27017:27017
volumes:
  mongodata:
