version: "3.9"
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      KC_DB: postgres
      KC_DB_URL: postgres:5432
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KEYCLOAK_ADMIN: ${KC_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - postgres
    entrypoint: "/opt/keycloak/bin/kc.sh start --proxy=edge --http-relative-path=auth"
    network_mode: "host"
volumes:
  postgres_data:
    driver: local